apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: external-dns-operator
  name: external-dns-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-operator
  namespace: external-dns-operator
  labels:
    name: external-dns-operator
spec:
  selector:
    matchLabels:
      name: external-dns-operator
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: external-dns-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: external-dns-operator
        image: quay.io/openshift/origin-external-dns-operator:latest
        args:
        - --metrics-bind-address=127.0.0.1:8080
        - --operator-namespace=$(OPERATOR_NAMESPACE)
        - --operand-namespace=$(OPERATOR_NAMESPACE)
        - --externaldns-image=$(RELATED_IMAGE_EXTERNAL_DNS)
        - --trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)
        - --leader-elect
        - --webhook-disable-http2
        terminationMessagePolicy: FallbackToLogsOnError
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_EXTERNAL_DNS
          # openshift/external-dns commit: 8da2509b922d50ef7b1b8ea2297758888f32448d
          # manifest link: https://quay.io/repository/external-dns-operator/external-dns/manifest/sha256:42c9f6d6b01d5e45b7d5064d2d6dea1f7b51346198d80e7f7f9821bd7fd072cf
          value: quay.io/external-dns-operator/external-dns@sha256:42c9f6d6b01d5e45b7d5064d2d6dea1f7b51346198d80e7f7f9821bd7fd072cf
        - name: TRUSTED_CA_CONFIGMAP_NAME
        securityContext:
          capabilities:
            drop:
            - "ALL"
          privileged: false
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: "RuntimeDefault"
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
      serviceAccountName: external-dns-operator
